// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6872.FRC2019.commands;

import edu.wpi.first.wpilibj.command.TimedCommand;
import org.usfirst.frc6872.FRC2019.Robot;
import org.usfirst.frc6872.FRC2019.subsystems.Tower;

/**
 *
 */
public class MoveWinchTimed extends TimedCommand {

    private double speed;

    public MoveWinchTimed() {
        this(0);
    }

    public MoveWinchTimed(double timeout) {
        super(Math.abs(timeout));

        speed = -Math.signum(timeout) * Tower.diskSpeed;

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.tower);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.tower.moveManually(speed);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        Robot.tower.moveManually(speed);
    }


    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.tower.stopMotor();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        Robot.tower.stopMotor();
    }
}
