// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6872.FRC2019;

import org.usfirst.frc6872.FRC2019.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc6872.FRC2019.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton valveButton;
    public JoystickButton grabDisk;
    public JoystickButton releaseDisk;
    public JoystickButton grabBall;
    public JoystickButton releaseBall;
    public Joystick joystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick = new Joystick(0);
        
        releaseBall = new JoystickButton(joystick, 1);
        releaseBall.whenPressed(new SetGripper(Gripper.ballOpen));
        grabBall = new JoystickButton(joystick, 1);
        grabBall.whenPressed(new SetGripper(Gripper.ballClose));
        releaseDisk = new JoystickButton(joystick, 1);
        releaseDisk.whenPressed(new SetGripper(Gripper.diskClose));
        grabDisk = new JoystickButton(joystick, 1);
        grabDisk.whenPressed(new SetGripper(Gripper.diskOpen));
        valveButton = new JoystickButton(joystick, 8);
        valveButton.whenPressed(new ToggleValve());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Drive With Joysticks", new DriveWithJoysticks());
        SmartDashboard.putData("Set Valve: Open Valve", new SetValve(true));
        SmartDashboard.putData("Set Valve: Close Valve", new SetValve(false));
        SmartDashboard.putData("Toggle Valve", new ToggleValve());
        SmartDashboard.putData("Set Gripper: Grab Disk", new SetGripper(Gripper.diskOpen));
        SmartDashboard.putData("Set Gripper: Release Disk", new SetGripper(Gripper.diskClose));
        SmartDashboard.putData("Set Gripper: Grab Ball", new SetGripper(Gripper.ballClose));
        SmartDashboard.putData("Set Gripper: Release Ball", new SetGripper(Gripper.ballOpen));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick() {
        return joystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

